server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: bidding-service

bidders:
  urls: http://localhost:8081, http://localhost:8082, http://localhost:8083
  connection:
    connect-timeout: 5
    read-timeout: 5

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 1s

logging:
  level:
    com.yieldlab.biddingservice: INFO