server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: bidding-service

bidders:
  urls: http://localhost:8081, http://localhost:8082, http://localhost:8083
  connection:
    connect-timeout: 5
    read-timeout: 5

resilience4j:
  retry:
    instances:
      postBidderRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.net.ConnectException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException

logging:
  level:
    com.yieldlab.biddingservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus